### ISSUE TITLE
_super is undefined if property isn't explicitly defined

### ISSUE THREAD

**Issue by imjoshdean** [canjs/can-construct-super#11]
This seems to have been introduced in `3.0.1`. Consider the following example:

```js
var Parent = Construct.extend({ });

var Child = Parent.extend({
  init: function () {
    this._super(arguments);
  }
});
```

In 3.0.0, this worked, but now the get the error `this._super is not a function`.

Breaking test:

```js
test("_super works if property isn't explicitly defined", function () {
	var Parent = Construct.extend({
	});

	var Child = Parent.extend({
		init: function () {
			this._super();
			ok(true);
		}
	});
	new Child();
});
```

**Comment by justinbmeyer** [comment]
I'm sorta surprised this worked previously.  This will always be a no-op right?

**Comment by justinbmeyer** [comment]
Ah, the bug wasn't what I thought it was.  The problem is that we might need to walk up the `proto` chain to make this work ... which kind of stinks.  Might need to see what IE9 supports.
